# Generated by Django 4.1.1 on 2022-09-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=64, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=128, verbose_name="Last Name"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Manuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "date_submission",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Submission"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="", verbose_name="Manuscript file"),
                ),
                ("author", models.ManyToManyField(to="registry.author")),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manuscript",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.manuscript",
                    ),
                ),
            ],
        ),
    ]
