# Generated by Django 4.1.2 on 2022-10-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="reviewer_id",
        ),
        migrations.AddField(
            model_name="author",
            name="is_reviewer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="author_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registry.author",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="number_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="sum_votes",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="date_submission",
            field=models.DateTimeField(verbose_name="Date Submission"),
        ),
        migrations.DeleteModel(
            name="Reviewer",
        ),
    ]
