# Generated by Django 4.1.2 on 2022-10-17 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manuscript",
            old_name="author",
            new_name="authors",
        ),
    ]
