# Generated by Django 4.1.2 on 2022-11-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_remove_review_reviewer_id_author_is_reviewer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="walletaddress",
            name="user_id",
        ),
        migrations.AddField(
            model_name="walletaddress",
            name="author_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="registry.author",
            ),
        ),
    ]
