# Generated by Django 4.1.2 on 2022-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0003_remove_walletaddress_user_id_walletaddress_author_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="date_submission",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date Submission"
            ),
        ),
    ]
