# Generated by Django 4.1.2 on 2022-11-19 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_alter_manuscript_date_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
