# Generated by Django 4.1.2 on 2022-12-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0004_alter_manuscript_date_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
